name: Push and Deploy the Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          # This path is totally independant from the 'file' directve below
          context: ./
          # This path is totally independant from the 'context' directive above
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task8_docker:latest
  
  deploy:
    runs-on: ubuntu-latest   
    needs: [build-and-push]
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        # TODO: add env vars as secrets on GitHub
        with:
          # VPS IP
          host: ${{ secrets.VPS_SSH_HOST }}
          # VPS username
          username: ${{ secrets.VPS_SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          key: ${{ secrets.VPS_SSH_SECRET }}
          # SSH port
          script: |
            echo "Pull new image"
            docker-compose -f ./morald/task8_docker/docker-compose.yml pull
            echo "Restart the container"
            docker-compose -f ./morald/task8_docker/docker-compose.yml up --force-recreate --build --no-deps -d
            echo "Delete old image"
            docker image prune -f
